language: java
sudo: required
services:
  - docker
branches:
  only:
    - master
    - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "OpenJDK 8"
      jdk: openjdk8
      script: mvn -q clean verify -B
